### ISSUE TITLE
[Feature Request] Please add up down upload download style. 

### ISSUE THREAD

**Issue by tazihad** [rishuinfinity/InternetSpeedMonitor#1]
An option to enable Download and upload speed by up down. Not side by side.
like this.
![hqdefault](https://user-images.githubusercontent.com/19417232/164611884-7a8ff462-7525-49a8-b65e-930cff9f1d28.jpg)

**Comment by rishuinfinity** [comment]
Hey, I currently don't have a stable concrete solution for it, but you can try the following to achieve this.

Replace 
```
    if(settings.get_boolean('separate-format'))
    {
      finaltext += "↑ " + netSpeedFormat(uploadSpeed) + " ↓ " + netSpeedFormat(downloadSpeed);
    } else {
      finaltext += "⇅ " + netSpeedFormat(uploadSpeed+downloadSpeed);
    }
```
with
```
    if(settings.get_boolean('separate-format'))
    {
      finaltext += "↑ " + netSpeedFormat(uploadSpeed) + "\n↓ " + netSpeedFormat(downloadSpeed);
    } else {
      finaltext += "⇅ " + netSpeedFormat(uploadSpeed+downloadSpeed);
    }
```
in ~/.local/share/gnome-shell/extensions/InternetSpeedMonitor@Rishu

Make sure that your panel height is enough to show both lines, otherwise increase the panel height or decrease your font size.

If I am able to find a stable solution, then I'll update the extension with it in the future.
