### ISSUE TITLE
Increase font size

### ISSUE THREAD

**Issue by S8D** [rishuinfinity/InternetSpeedMonitor#6]
Hello Rishu Raj,
Thank you for taking the time to write a useful tweak to contribute to the linux community. I have a few questions below, hope you answer.
How can I change the font size, as well as change the Mbps and Mb/s values?
Thank you.

**Comment by rishuinfinity** [comment]
You can change the font size by adding this line in the enable function in extension.js

![image](https://user-images.githubusercontent.com/43110247/201471955-24f577de-b4db-4151-a091-ca119739e193.png)

And in order to change the default unit text, you can edit this line where all units are declared:

![image](https://user-images.githubusercontent.com/43110247/201472003-f7bc0d86-ef68-4ed9-a66b-403eeac485ac.png)


I hope this answers your questions

**Comment by S8D** [comment]
I have successfully increased the font size.
Looking forward to the next version you will add those custom features to the gnome menu.
Thank you.

**Comment by rishuinfinity** [comment]
:+1:
